### ISSUE TITLE
new post templates are not applied on blog posts

### ISSUE THREAD

**Issue by nidhi-wgl** [forestryio/novela-hugo-starter#6]
I created an template for posts without hero image and applied to the post. Yet i see blank space after title.

Checked the theme code, sorry i couldn't find where you are selecting template for the posts. I am new to Hugo and Gatsby.

I have also one more issue, if we add field to Home or Home Hero in front matter templates, the markdown file is appended with all fields including new one rather than just adding new one to table. The new field is also not getting displayed.

**Comment by DirtyF** [comment]
Hi, it's not because your add fields in Forestry, that they will be displayed in your site, you'll still have to update your layouts to reflects those changes. Forestry is responsible for creating or updating your content, not displaying it. Everything you describe here is perfectly normal and expected.
